volumes:
  local_postgres_data: {}

services:

  db:
    image: postgres:15
    container_name: zentric_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zentric
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure